### ISSUE TITLE
[1.11.2] crash at at shadows.plants.util.Util.getStateByChance(Util.java:321) 

### ISSUE THREAD

**Issue by PrinceOfAmber** [Shadows-of-Fire/Plants#17]
Installed was 

Plants-1.11.2-beta-0.8.4.jar

Full log

http://pastebin.com/TDTPe0Fw

In that log file around line 1482 it says

java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block plants:cataplant, it is not an allowed value
at pl.asie.foamfix.common.FoamyBlockState.func_177226_a(FoamyBlockState.java:34) ~[foamfix-0.6.2-beta2-anarchy.jar:?]
at shadows.plants.util.Util.getStateByChance(Util.java:321) ~[Util.class:?]
at shadows.plants.util.Decorator.onWorldDecoration(Decorator.java:35) ~[Decorator.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_524_Decorator_onWorldDecoration_Decorate.invoke(.dynamic) ~[?:?]

**Comment by Shadows-of-Fire** [comment]
Fixed in 0.8.5

**Comment by PrinceOfAmber** [comment]
That was quick, thanks!
