### ISSUE TITLE
Invalid name craashes client

### ISSUE THREAD

**Issue by beesyndicate** [Shadows-of-Fire/Plants#31]
When harvesting a Cedar log with an enchanted axe causes a block with a missing texture to drop.
If you place the block the Minecraft client crashes.

java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 7, Size: 4
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
    at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
    at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.IndexOutOfBoundsException: Index: 7, Size: 4
    at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_131]
    at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_131]
    at shadows.plants2.block.BlockEnumLog.getStateForPlacement(BlockEnumLog.java:78) ~[BlockEnumLog.class:?]
    at shadows.plants2.itemblock.ItemBlockEnum.func_180614_a(ItemBlockEnum.java:35) ~[ItemBlockEnum.class:?]
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:845) ~[ForgeHooks.class:?]
    at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
    at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:478) ~[or.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
    at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
    ... 5 more
[15:11:49] [Server thread/INFO]: Bee_Syndicate lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer

**Comment by Shadows-of-Fire** [comment]
Huh.  What enchantments were on the axe?

**Comment by beesyndicate** [comment]
Unbreaking III
Silk Touch 

https://clips.twitch.tv/IntelligentSmoggyDonkeySoonerLater

**Comment by beesyndicate** [comment]
also this

https://www.youtube.com/watch?v=3DrDdimdRgA&feature=youtu.be

**Comment by beesyndicate** [comment]
It appears to be any axe with silk touch that causes this

**Comment by Shadows-of-Fire** [comment]
Yeah its an issue with minecraft allowing any full block to be silk touched by default, which breaks this.  Fix is coming

**Comment by beesyndicate** [comment]
Cool Ty and keep me updated. Is this a Plants fix or a Mojang fix?

**Comment by Shadows-of-Fire** [comment]
Version 2.0.3 pending to curse.  Weird that silk touch doesn't default to off.

**Comment by beesyndicate** [comment]
Yea you would think that if a block needs that flag that you would make the distinction to on at the block level as in "yes this block can be silk touched"
