### ISSUE TITLE
1.12 Crash

### ISSUE THREAD

**Issue by Wissi** [Shadows-of-Fire/Plants#43]
Having a crash with issue:
[23:26:03] [main/FATAL] [FML]: The following problems were captured during this phase
[23:26:03] [main/ERROR] [FML]: Caught exception from plants2 (java.lang.ArrayIndexOutOfBoundsException: 32767)

```
WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.5.1.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.1.7.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.4.jar)
  AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  DLFMLCorePlugin (DynamicLights-1.12.1.jar)
  BCModPlugin (backpacks 1.12.2 - 3.3.2.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  LoadingPlugin (Quark-r1.3-112.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  OpenEyePlugin (OpenEye-1.12.1-0.8.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ComfortsCoreLoadingPlugin (comforts-1.12.2-0.0.8-rc2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 11/15/17 11:26 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Plants (plants2)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 32767
	at biomesoplenty.common.block.BlockBOPLilypad.func_176203_a(BlockBOPLilypad.java:108)
	at biomesoplenty.common.item.ItemBOPBlock.func_77667_c(ItemBOPBlock.java:85)
	at net.minecraft.item.Item.func_77657_g(Item.java:292)
	at net.minecraft.item.Item.func_77653_i(Item.java:362)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at com.kashdeya.tinyprogressions.main.TinyProgressions.registerOre(TinyProgressions.java:125)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_730_TinyProgressions_registerOre_OreRegisterEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:683)
	at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
	at shadows.plants2.init.ModRegistry.oreDict(ModRegistry.java:253)
	at shadows.plants2.Plants2.init(Plants2.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:719)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:348)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
```

**Comment by Shadows-of-Fire** [comment]
update tiny progressions

**Comment by Wissi** [comment]
Thank you ssoooo much. It works perfectly fine now. Love you mod so much.
