### ISSUE TITLE
Biome - Crystal Forest - Need help about compatibility

### ISSUE THREAD

**Issue by alxcool** [Shadows-of-Fire/Plants#55]
Hello! I really enjoy this mod and have already took the achivement of recovering every possible plants. Unfortunatly I was unable to find any "crystal" related items, so far.

Background : I play as single players, on forge (2603) using the old minecraft launcher (graphic card issue). With a custom set of 100 mods, no packs. Windows 7 64 bits, 8G ram, Core i7...

Issue : Today I have used the "Nature compas mod"' item in order to find a biome called "Crystal Forest". 
*This one was able to give me the direction of this biome, but unfortunately, in a sector already explored.

So I've check, open the config file in my minecraft folder, and the toggle about this biome was already set to true. I will try to search for a second copy of this biome in a unexplored, unloaded area, but for now It may be a bug. Because this biome have been registered as "Vanilla Forest Biome", or replaced by it. I'm not so sure if this is an issue, because this section of my world may have been created before I install the "plants2" mod.**

That said, I will run a few tests to keep you informed, and I would like to offer my help to develop the wiki section on this site and offer my help to find the most appropriate temperature range for each plant, individually.

*Sorry for my lack of grammar as english is not my first language. Feel free to ask, I could edit my comment if you need!

**Can't find a easy way to list all my mod except using a crash log. So Here is a sample of log file instead : 
[11:42:36] [main/INFO]: Setting user: Al_Cool
[11:42:41] [main/INFO]: LWJGL Version: 2.9.4
[11:42:49] [main/INFO]: Reloading ResourceManager: The 5zig Mod, Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:mercurius_updater, FMLFileResourcePack:Animania, FMLFileResourcePack:AppleSkin, FMLFileResourcePack:Armor Sound Tweak, FMLFileResourcePack:Aroma1997Core, FMLFileResourcePack:AromaBackup, FMLFileResourcePack:AromaBackuprecovery, FMLFileResourcePack:B.A.S.E, FMLFileResourcePack:Baubles, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:Block Drops, FMLFileResourcePack:Bloodmoon, FMLFileResourcePack:Carbonado, FMLFileResourcePack:Carry On, FMLFileResourcePack:Ceramics, FMLFileResourcePack:Clumps, FMLFileResourcePack:Cooking for Blockheads, FMLFileResourcePack:Coralreef, FMLFileResourcePack:Craftable Horse Armour [CHA&S], FMLFileResourcePack:CraftStudio API, FMLFileResourcePack:CreativeCore, FMLFileResourcePack:CustomNPCs, FMLFileResourcePack:Default Options, FMLFileResourcePack:Dense Metals, FMLFileResourcePack:Diet Hopper, FMLFileResourcePack:Dooglamoo Worlds, FMLFileResourcePack:Duckcraft, FMLFileResourcePack:Enhanced Visuals, FMLFileResourcePack:Fairy Lights, FMLFileResourcePack:Fast Leaf Decay, FMLFileResourcePack:ForageCraft, FMLFileResourcePack:FTBLib, FMLFileResourcePack:Giacomo's Foundry, FMLFileResourcePack:Giacomo's Bookshelves Mod, FMLFileResourcePack:Giacomo's compass, FMLFileResourcePack:Fishing Net Mod, FMLFileResourcePack:Giacomo's maps, FMLFileResourcePack:Waila, FMLFileResourcePack:InGameConfigManager, FMLFileResourcePack:InGame Info XML, FMLFileResourcePack:Simple Inventory sorting, FMLFileResourcePack:Just Enough HarvestCraft, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:Jeivillagers, FMLFileResourcePack:Just Enough Resources, FMLFileResourcePack:Keyboard Wizard, FMLFileResourcePack:Level Up! Reloaded, FMLFileResourcePack:Lucky Block, FMLFileResourcePack:LunatriusCore, FMLFileResourcePack:Mantle, FMLFileResourcePack:Missing Pieces, FMLFileResourcePack:Misty World, FMLFileResourcePack:More Loot Tables, FMLFileResourcePack:Natura, FMLFileResourcePack:Nature's Compass, FMLFileResourcePack:NetherEx, FMLFileResourcePack:Nether Gold Ore, FMLFileResourcePack:Pam's Get all the Seeds!, FMLFileResourcePack:Pam's BoneCraft, FMLFileResourcePack:Pam's DesertCraft, FMLFileResourcePack:Pam's HarvestCraft, FMLFileResourcePack:Pam's Pig Skin, FMLFileResourcePack:Pam's Simple Recipes, FMLFileResourcePack:Pam's Clay Spawn, FMLFileResourcePack:PartyParrots, FMLFileResourcePack:Pet Bat, FMLFileResourcePack:Placeable Items Mod, FMLFileResourcePack:Placebo, FMLFileResourcePack:Plants, FMLFileResourcePack:Corail Recycleur, FMLFileResourcePack:Reliquary, FMLFileResourcePack:Roguelike Dungeons, FMLFileResourcePack:Roots 2, FMLFileResourcePack:Rustic, FMLFileResourcePack:Simple Ore Generation, FMLFileResourcePack:Sound Filters, FMLFileResourcePack:Stackie, FMLFileResourcePack:Stars Mod, FMLFileResourcePack:Tree Chopper, FMLFileResourcePack:Tumbleweed, FMLFileResourcePack:Vein Miner, FMLFileResourcePack:Mod Support, FMLFileResourcePack:Villager Market, FMLFileResourcePack:Villager Trade Tables, FMLFileResourcePack:Vulcanite, FMLFileResourcePack:Waddles, FMLFileResourcePack:Waila Harvestability, FMLFileResourcePack:Water Strainer, FMLFileResourcePack:Waystones, FMLFileResourcePack:Pam's Weee! Flowers, FMLFileResourcePack:WrapUp, FMLFileResourcePack:Xaero's World Map, FMLFileResourcePack:YABBA
[11:43:11] [Sound Library Loader/INFO]: Starting up SoundSystem...
[11:43:11] [Thread-10/INFO]: Initializing LWJGL OpenAL
[11:43:11] [Thread-10/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[11:43:12] [Thread-10/INFO]: OpenAL initialized.
[11:43:12] [Sound Library Loader/INFO]: Sound engine started
[11:43:16] [main/WARN]: Unable to resolve texture due to upward reference: #tex in yabba:models/item/upgrade_base.json
[11:43:19] [main/INFO]: Created: 2048x1024 textures-atlas
[11:43:23] [main/WARN]: Unable to resolve texture due to upward reference: #none_bot in minecraft:models/block/cross.json
[11:43:23] [main/WARN]: Unable to resolve texture due to upward reference: #none_top in minecraft:models/block/cross.json
[11:43:41] [main/INFO]: Narrator library for x64 successfully loaded
[11:43:56] [Server thread/INFO]: Starting integrated minecraft server version 1.12.2
[11:43:56] [Server thread/INFO]: Generating keypair
[11:43:59] [Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/food/pumpkin_pie
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:pumpkin_pie'
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
	at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:95) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[11:43:59] [Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/food/mushroom_stew
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:mushroom_stew'
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
	at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:95) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[11:43:59] [Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/food/cookie
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:cookie'
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
	at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:95) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[11:43:59] [Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/food/bread
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:bread'
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
	at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:95) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[11:43:59] [Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/food/beetroot_soup
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:beetroot_soup'
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
	at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:184) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:95) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[11:44:00] [Server thread/INFO]: Loaded 909 advancements
[11:44:00] [Server thread/INFO]: Preparing start region for level 0
[11:44:01] [Server thread/INFO]: Preparing spawn area: 0%
[11:44:02] [Server thread/WARN]: Keeping entity animania:chick_leghorn that already exists with UUID 1a8ab620-93e1-4915-bf68-1259d5311df7
[11:44:02] [Server thread/WARN]: Keeping entity animania:ram_friesian that already exists with UUID ea8050cc-95d1-40e7-b83d-c1b9dcc5ab3b
[11:44:02] [Server thread/WARN]: Keeping entity animania:ewe_jacob that already exists with UUID 6c802b9d-f50a-47a9-b09e-15097cb7b315
[11:44:02] [Server thread/INFO]: Preparing spawn area: 60%
[11:44:03] [Aromabackup-Backup/INFO]: [§1AromaBackup§r] Starting Backup. The world may lag for a bit!
[11:44:04] [Server thread/INFO]: Changing view distance to 8, from 10
[11:44:05] [Server thread/INFO]: Al_Cool[local:E:65bd0806] logged in with entity id 739 at (142.7214988483181, 69.5, 2.321607185498669)
[11:44:05] [Server thread/INFO]: Al_Cool joined the game
[11:44:05] [Server thread/INFO]: Saving and pausing game...
[11:44:09] [Thread-9/INFO]: [CHAT] §2CustomNpcs§f installed. For more info §9§nClick here
[11:44:09] [Server thread/INFO]: Saving chunks for level 'The 70's'/overworld
[11:44:09] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_nether
[11:44:09] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_end
[11:44:09] [Server thread/INFO]: Saving chunks for level 'The 70's'/misty_world
[11:44:10] [main/INFO]: [CHAT] Veinminer set to deactivate on sneak.
[11:44:10] [main/INFO]: [CHAT] Veinminer client keybind disabled.
[11:44:10] [main/INFO]: Loaded 639 advancements
[11:44:10] [Aromabackup-Backup/INFO]: ThreadedAnvilChunkStorage (The 70's): All chunks are saved
[11:44:10] [Aromabackup-Backup/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[11:44:10] [Aromabackup-Backup/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[11:44:10] [Aromabackup-Backup/INFO]: ThreadedAnvilChunkStorage (DIM69): All chunks are saved
[11:44:11] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 6739ms behind, skipping 134 tick(s)
[11:44:15] [Server thread/INFO]: Saving and pausing game...
[11:44:15] [Server thread/INFO]: Saving chunks for level 'The 70's'/overworld
[11:44:15] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_nether
[11:44:15] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_end
[11:44:15] [Server thread/INFO]: Saving chunks for level 'The 70's'/misty_world
[11:45:13] [Server thread/INFO]: Saving and pausing game...
[11:45:13] [Server thread/INFO]: Saving chunks for level 'The 70's'/overworld
[11:45:14] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_nether
[11:45:14] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_end
[11:45:14] [Server thread/INFO]: Saving chunks for level 'The 70's'/misty_world
[11:47:27] [Aromabackup-Backup/INFO]: [§1AromaBackup§r] World Backup done!
[11:47:28] [main/INFO]: [CHAT] [§1AromaBackup§r] World Backup done!
[11:47:32] [Server thread/INFO]: Saving and pausing game...
[11:47:32] [Server thread/INFO]: Saving chunks for level 'The 70's'/overworld
[11:47:32] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_nether
[11:47:32] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_end
[11:47:32] [Server thread/INFO]: Saving chunks for level 'The 70's'/misty_world
[11:49:25] [Server thread/INFO]: Saving and pausing game...
[11:49:25] [Server thread/INFO]: Saving chunks for level 'The 70's'/overworld
[11:49:25] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_nether
[11:49:25] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_end
[11:49:26] [Server thread/INFO]: Saving chunks for level 'The 70's'/misty_world
[11:49:40] [Server thread/INFO]: Saving and pausing game...
[11:49:40] [Server thread/INFO]: Saving chunks for level 'The 70's'/overworld
[11:49:41] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_nether
[11:49:41] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_end
[11:49:41] [Server thread/INFO]: Saving chunks for level 'The 70's'/misty_world
[11:49:54] [Server thread/INFO]: Saving and pausing game...
[11:49:54] [Server thread/INFO]: Saving chunks for level 'The 70's'/overworld
[11:49:55] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_nether
[11:49:55] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_end
[11:49:55] [Server thread/INFO]: Saving chunks for level 'The 70's'/misty_world
[11:52:42] [Server thread/INFO]: Saving and pausing game...
[11:52:42] [Server thread/INFO]: Saving chunks for level 'The 70's'/overworld
[11:52:42] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_nether
[11:52:42] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_end
[11:52:42] [Server thread/INFO]: Saving chunks for level 'The 70's'/misty_world
[11:52:53] [Server thread/INFO]: Saving and pausing game...
[11:52:53] [Server thread/INFO]: Saving chunks for level 'The 70's'/overworld
[11:52:54] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_nether
[11:52:54] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_end
[11:52:54] [Server thread/INFO]: Saving chunks for level 'The 70's'/misty_world
[11:56:03] [Server thread/INFO]: Saving and pausing game...
[11:56:03] [Server thread/INFO]: Saving chunks for level 'The 70's'/overworld
[11:56:03] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_nether
[11:56:03] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_end
[11:56:03] [Server thread/INFO]: Saving chunks for level 'The 70's'/misty_world
[11:56:04] [Server thread/INFO]: Stopping server
[11:56:04] [Server thread/INFO]: Saving players
[11:56:04] [Server thread/INFO]: Al_Cool lost connection: Disconnected
[11:56:04] [Server thread/INFO]: Al_Cool left the game
[11:56:04] [Server thread/INFO]: Stopping singleplayer server as player logged out
[11:56:04] [Server thread/INFO]: Saving worlds
[11:56:04] [Server thread/INFO]: Saving chunks for level 'The 70's'/overworld
[11:56:04] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_nether
[11:56:04] [Server thread/INFO]: Saving chunks for level 'The 70's'/the_end
[11:56:04] [Server thread/INFO]: Saving chunks for level 'The 70's'/misty_world
[11:56:18] [main/INFO]: Stopping!
[11:56:18] [main/INFO]: SoundSystem shutting down...
[11:56:18] [main/WARN]: Author: Paul Lamb, www.paulscode.com

**Comment by alxcool** [comment]
Successful discovery! I was abble to recover the items listed in JEI. Thk for reading this. If I could suggest to visit this biome at night, and equip yourself with silktouch tools and shears. I was as amazed as the first time I've found a mushroom island!

Let me know If I could Help with the wiki or with some plants, information!

**Comment by Shadows-of-Fire** [comment]
Yeah, as far as the wiki goes, once upon a time I started working on it and I ended up with other things to do, and never got back to it.  I will leave the wiki up for public edits, if you wish to work on it.
